// packages/solid/src/components/Container/index.tsx
import {
  type ParentProps,
  createEffect,
  createSignal,
  onCleanup,
} from "solid-js";
import "../../theme.css";
import { classNames } from "../../utils";
import { Link } from "../Link";
import s from "./container.module.css";

type ContainerProps = ParentProps<{
  href?: string;
}>;

export function Container(props: ContainerProps) {
  let ref: HTMLDivElement | null = null;
  const [prevHeight, setPrevHeight] = createSignal(0);

  createEffect(() => {
    if (ref) {
      const observer = new ResizeObserver((entries) => {
        const entry = entries[0];
        if (!entry) return;

        let { height } = entry.contentRect;
        height += 2; // Add borders
        if (height !== prevHeight()) {
          setPrevHeight(height);
          window.parent.postMessage(
            {
              height,
              id: new URLSearchParams(window.location.search).get("id"),
            },
            "*",
          );
        }
      });
      observer.observe(ref);

      onCleanup(() => observer.disconnect());
    }
  });

  const handleInteraction = () => {
    if (ref && props.href) {
      const anchor = ref.querySelector("a");
      if (anchor) {
        (anchor as HTMLAnchorElement).click();
      }
    }
  };

  return (
    <div
      // biome-ignore lint/suspicious/noAssignInExpressions: <explanation>
      ref={(el) => (ref = el)}
      class={classNames("bsky-react-post-theme", s.container)}
      onClick={handleInteraction}
      onKeyDown={handleInteraction}
    >
      {props.href && <Link href={props.href} />}
      <div class={s.article}>{props.children}</div>
    </div>
  );
}

// packages/core/src/component/Container.tsx
import { type PropsWithChildren, useEffect, useRef } from "react";
import { eventHandler } from "../utils";
import { Link } from "./Link";
import "../theme.css";

export type ContainerProps = PropsWithChildren<{
  href?: string;
}>;

export function Container({ children, href }: ContainerProps) {
  const ref = useRef<HTMLDivElement>(null);
  const prevHeight = useRef(0);

  useEffect(() => {
    if (ref.current) {
      const observer = new ResizeObserver((entries) => {
        const entry = entries[0];
        if (!entry) return;

        let { height } = entry.contentRect;
        height += 2; // border top and bottom
        if (height !== prevHeight.current) {
          prevHeight.current = height;
          window.parent.postMessage(
            {
              height,
              id: new URLSearchParams(window.location.search).get("id"),
            },
            "*",
          );
        }
      });
      observer.observe(ref.current);
      return () => observer.disconnect();
    }
  }, []);

  const handleInteraction = eventHandler(() => {
    if (ref.current && href) {
      const anchor = ref.current.querySelector("a");
      if (anchor) {
        anchor.click();
      }
    }
  });

  return (
    <div
      ref={ref}
      className="react-bluesky-theme w-full bg-[var(--post-bg-color)] hover:bg-[var(--post-bg-color-hover)] relative transition-colors max-w-[600px] min-w-[300px] flex border rounded-xl"
      onClick={handleInteraction}
      onKeyDown={handleInteraction}
    >
      {href && <Link href={href} />}
      <div className="flex-1 px-4 pt-3 pb-2.5">{children}</div>
    </div>
  );
}
